// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/timer.dart';
import 'models/work_day.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 8878881212663892259),
    name: 'Timer',
    lastPropertyId: const obx_int.IdUid(14, 1454942602827157656),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3162685269841975031),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1211442299714754229),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1867550159219796890),
        name: 'project',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1395349291315852533),
        name: 'branchName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4876211788415565489),
        name: 'url',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8253277892578516086),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1673881918574406862),
        name: 'startDateTime',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 7462556967149489344),
        name: 'endDateTime',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 5209677092141841374),
        name: 'isComplete',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 5904951434007563102),
        name: 'estimateMilliseconds',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 7596249690752704828),
        name: 'durationLeftMilliseconds',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 6116520999441361770),
        name: 'number',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 1454942602827157656),
        name: 'description',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 4933970297554397750),
    name: 'WorkDay',
    lastPropertyId: const obx_int.IdUid(7, 4790071892462647154),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6780529735785071102),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1875194980588651582),
        name: 'debtOfTimeMilliseconds',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2161710772604692635),
        name: 'freeTimeMilliseconds',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2965669944288612960),
        name: 'prevWorkTimeMilliseconds',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8632302990430822171),
        name: 'createToDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1474380091999469571),
        name: 'startWorkDateTime',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4790071892462647154),
        name: 'endWorkDateTime',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 4933970297554397750),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [504788194762753626],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Timer: obx_int.EntityDefinition<Timer>(
      model: _entities[0],
      toOneRelations: (Timer object) => [],
      toManyRelations: (Timer object) => {},
      getId: (Timer object) => object.id,
      setId: (Timer object, int id) {
        object.id = id;
      },
      objectToFB: (Timer object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final projectOffset = object.project == null
            ? null
            : fbb.writeString(object.project!);
        final branchNameOffset = object.branchName == null
            ? null
            : fbb.writeString(object.branchName!);
        final urlOffset = object.url == null
            ? null
            : fbb.writeString(object.url!);
        final descriptionOffset = object.description == null
            ? null
            : fbb.writeString(object.description!);
        fbb.startTable(15);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, projectOffset);
        fbb.addOffset(3, branchNameOffset);
        fbb.addOffset(4, urlOffset);
        fbb.addInt64(5, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(6, object.startDateTime?.millisecondsSinceEpoch);
        fbb.addInt64(7, object.endDateTime?.millisecondsSinceEpoch);
        fbb.addBool(8, object.isComplete);
        fbb.addInt64(9, object.estimateMilliseconds);
        fbb.addInt64(11, object.durationLeftMilliseconds);
        fbb.addInt64(12, object.number);
        fbb.addOffset(13, descriptionOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final startDateTimeValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          16,
        );
        final endDateTimeValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          18,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final projectParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final branchNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final urlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 30);
        final startDateTimeParam = startDateTimeValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(
                startDateTimeValue,
                isUtc: true,
              );
        final object =
            Timer(
                name: nameParam,
                project: projectParam,
                branchName: branchNameParam,
                url: urlParam,
                description: descriptionParam,
                startDateTime: startDateTimeParam,
              )
              ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
              ..createdAt = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
                isUtc: true,
              )
              ..endDateTime = endDateTimeValue == null
                  ? null
                  : DateTime.fromMillisecondsSinceEpoch(
                      endDateTimeValue,
                      isUtc: true,
                    )
              ..isComplete = const fb.BoolReader().vTableGet(
                buffer,
                rootOffset,
                20,
                false,
              )
              ..estimateMilliseconds = const fb.Int64Reader().vTableGet(
                buffer,
                rootOffset,
                22,
                0,
              )
              ..durationLeftMilliseconds = const fb.Int64Reader().vTableGet(
                buffer,
                rootOffset,
                26,
                0,
              )
              ..number = const fb.Int64Reader().vTableGet(
                buffer,
                rootOffset,
                28,
                0,
              );

        return object;
      },
    ),
    WorkDay: obx_int.EntityDefinition<WorkDay>(
      model: _entities[1],
      toOneRelations: (WorkDay object) => [],
      toManyRelations: (WorkDay object) => {},
      getId: (WorkDay object) => object.id,
      setId: (WorkDay object, int id) {
        object.id = id;
      },
      objectToFB: (WorkDay object, fb.Builder fbb) {
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.debtOfTimeMilliseconds);
        fbb.addInt64(2, object.freeTimeMilliseconds);
        fbb.addInt64(3, object.prevWorkTimeMilliseconds);
        fbb.addInt64(4, object.createToDate.millisecondsSinceEpoch);
        fbb.addInt64(5, object.startWorkDateTime?.millisecondsSinceEpoch);
        fbb.addInt64(6, object.endWorkDateTime?.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final startWorkDateTimeValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final endWorkDateTimeValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          16,
        );
        final object = WorkDay()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..debtOfTimeMilliseconds = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            6,
            0,
          )
          ..freeTimeMilliseconds = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            8,
            0,
          )
          ..prevWorkTimeMilliseconds = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            10,
            0,
          )
          ..createToDate = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
          )
          ..startWorkDateTime = startWorkDateTimeValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(startWorkDateTimeValue)
          ..endWorkDateTime = endWorkDateTimeValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(endWorkDateTimeValue);

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Timer] entity fields to define ObjectBox queries.
class Timer_ {
  /// See [Timer.id].
  static final id = obx.QueryIntegerProperty<Timer>(_entities[0].properties[0]);

  /// See [Timer.name].
  static final name = obx.QueryStringProperty<Timer>(
    _entities[0].properties[1],
  );

  /// See [Timer.project].
  static final project = obx.QueryStringProperty<Timer>(
    _entities[0].properties[2],
  );

  /// See [Timer.branchName].
  static final branchName = obx.QueryStringProperty<Timer>(
    _entities[0].properties[3],
  );

  /// See [Timer.url].
  static final url = obx.QueryStringProperty<Timer>(_entities[0].properties[4]);

  /// See [Timer.createdAt].
  static final createdAt = obx.QueryDateProperty<Timer>(
    _entities[0].properties[5],
  );

  /// See [Timer.startDateTime].
  static final startDateTime = obx.QueryDateProperty<Timer>(
    _entities[0].properties[6],
  );

  /// See [Timer.endDateTime].
  static final endDateTime = obx.QueryDateProperty<Timer>(
    _entities[0].properties[7],
  );

  /// See [Timer.isComplete].
  static final isComplete = obx.QueryBooleanProperty<Timer>(
    _entities[0].properties[8],
  );

  /// See [Timer.estimateMilliseconds].
  static final estimateMilliseconds = obx.QueryIntegerProperty<Timer>(
    _entities[0].properties[9],
  );

  /// See [Timer.durationLeftMilliseconds].
  static final durationLeftMilliseconds = obx.QueryIntegerProperty<Timer>(
    _entities[0].properties[10],
  );

  /// See [Timer.number].
  static final number = obx.QueryIntegerProperty<Timer>(
    _entities[0].properties[11],
  );

  /// See [Timer.description].
  static final description = obx.QueryStringProperty<Timer>(
    _entities[0].properties[12],
  );
}

/// [WorkDay] entity fields to define ObjectBox queries.
class WorkDay_ {
  /// See [WorkDay.id].
  static final id = obx.QueryIntegerProperty<WorkDay>(
    _entities[1].properties[0],
  );

  /// See [WorkDay.debtOfTimeMilliseconds].
  static final debtOfTimeMilliseconds = obx.QueryIntegerProperty<WorkDay>(
    _entities[1].properties[1],
  );

  /// See [WorkDay.freeTimeMilliseconds].
  static final freeTimeMilliseconds = obx.QueryIntegerProperty<WorkDay>(
    _entities[1].properties[2],
  );

  /// See [WorkDay.prevWorkTimeMilliseconds].
  static final prevWorkTimeMilliseconds = obx.QueryIntegerProperty<WorkDay>(
    _entities[1].properties[3],
  );

  /// See [WorkDay.createToDate].
  static final createToDate = obx.QueryDateProperty<WorkDay>(
    _entities[1].properties[4],
  );

  /// See [WorkDay.startWorkDateTime].
  static final startWorkDateTime = obx.QueryDateProperty<WorkDay>(
    _entities[1].properties[5],
  );

  /// See [WorkDay.endWorkDateTime].
  static final endWorkDateTime = obx.QueryDateProperty<WorkDay>(
    _entities[1].properties[6],
  );
}
